# Generated by Django 3.0.1 on 2020-01-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomerInfo', '0002_auto_20200124_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desireinfo',
            name='cover',
            field=models.ImageField(blank=True, default='', null=True, upload_to='info/covers/'),
        ),
        migrations.AlterField(
            model_name='desireinfo',
            name='pdf',
            field=models.FileField(default='', upload_to='info/pdfs/'),
        ),
    ]
