# Generated by Django 3.0.1 on 2020-01-23 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customization', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Customer',
        ),
    ]
